development:
  adapter: postgresql
  encoding: unicode
  database: doc_manager_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: doc_manager_test
  pool: 5
  username: postgres
  password: 
