
production:
  adapter: postgresql
  encoding: unicode
  database: transparency
  pool: 5
  username: transparency
  password: b2aa167120c96770c82b18c5c0460795

development:
  adapter: postgresql
  encoding: unicode
  database: transparency
  pool: 5
  username: transparency
  password: b2aa167120c96770c82b18c5c0460795