
production:
  adapter: postgresql
  encoding: unicode
  database: transparency
  pool: 5
  username: transparency
  password: 41149952198542de91f8a3d9771feb32

development:
  adapter: postgresql
  encoding: unicode
  database: transparency
  pool: 5
  username: transparency
  password: 41149952198542de91f8a3d9771feb32